spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_board
    username: root
    password: hilg456
  liquibase:
    change-log: classpath*:db/change-log.xml

program:
  pictures:
    file:
      path: C:/Users/Dell/IdeaProjects/job-board/src/programfiles