spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 967542614813689
            client-secret: 0d8886e762df1a9d3c367d42a511e44e
            scope:
              - email
              - public_profile

          google:
            client-id: 74863290846-i5sth07msc4s0puqgouv0gpf5r9thrvn.apps.googleusercontent.com
            client-secret: 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
            scope:

          github:
            client-id: Ov23li9yjofRhQGEAqyY
            client-secret: f0f680ae58ec6d5140c034367b5297f015d88603
            scope:
              - read:user
              - user:email

  datasource:
    url: jdbc:mysql://localhost:3306/job_board
    username: root
    password: root

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: jobboardofficial@gmail.com
    password: zvfekdljbyxqplsw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  liquibase:
    change-log: classpath*:db/change-log.xml

program:
  pictures:
    file:
      path: C:\Users\aperk\IdeaProjects\job-bord\programfiles

password:
  user-password: "$2a$10$93TR3YWe4YTMfkgTV/6IÎÑ∑∂∫∆ƒ©˙¬˚µ≤≥÷œ∑´®†¥¨ˆøπ“‘åß∂ƒ©˙
                  †¥¨¨ˆøπ“‘åß∂©˙¬˚µ≤≥÷Ω≈ç√∫µ≤≥÷Ω∫ƒ∆∑´®†¥¨¨ˆøπ“‘åß∂©˙¬˚µ≤≥÷Ω≈ç√∫
                  $2a$10$qZYpy6yba88mXIYzAldIYu8U8EbJ4G/xxifzj2xzYcHVYskYwxpkm
                  ç√∫~µ≤≥÷Ω∫ƒ∆∑´®†¥¨¨ˆøπ“‘åß∂©˙¬˚µ≤≥÷Ω≈ç√∫"
